=== fcosueza/DAW/LMSGI/Tareas/Tema 4/complementarias/comp3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento vacio simple (solo para aumentar la legibilidad) -->

  <xs:element name="acceso_ssh">
    <xs:complexType />
  </xs:element>
  

  <!-- Elemento Principal -->

  <xs:element name="usuarios">
    <xs:complexType>

      <xs:sequence>
        <xs:element name="usuario" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>

            <xs:sequence>
              <xs:element name="identificador" type="xs:ID" />
              <xs:element name="contrasena" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element ref="acceso_ssh" minOccurs="0" maxOccurs="1"/>
              <xs:element name="carpeta" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>

          </xs:complexType>
        </xs:element>
      </xs:sequence>

    </xs:complexType>
  </xs:element>

</xs:schema>

=== fcosueza/DAW/LMSGI/Tareas/Tema_2/complementarias/comp3.xml
<?xml version="1.0" encoding="UTF-8"?>

<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="comp3.xsd">

    <usuario>
        <identificador>root</identificador>
        <contrasena>1234</contrasena>
        <acceso_ssh/>
    </usuario>
    <usuario>
        <identificador>newbie</identificador>
        <contrasena>S3gur1D4A_Xtr3m4</contrasena>
        <carpeta>home</carpeta>
        <carpeta>system</carpeta>
        <carpeta>temp</carpeta>
    </usuario>
</usuarios>
